### ISSUE TITLE
Alpha Release Checklist

### ISSUE THREAD

**Issue by balmas** [alpheios-project/webextension#39]
- [x] Latin Inflection Tables: Remove prototype flex grid table pieces (Kirill)
 - [x] Latin Inflection Tables: Link Footnotes (Kirill) (https://github.com/alpheios-project/inflection-tables/issues/12)
 - [x] Latin Inflection Tables: clean up display (verbs table is misaligned)
 - [x] Inflection Tables: Make sure highlighting works (Bridget to review)
 - [x] Lexicons: add choice of lexicon(s) per language to settings panel (Bridget to do, Kirill to review)
 - [x] Lexicons: add ability to filter lexicon query by user selection (Bridget to do, Kirill to review) (https://github.com/alpheios-project/lexicon-client/issues/5)
 - [x] Lexicons: add ability to lookup original form in addition to morphological form, option per language (Bridget to do, Kirill to review)
 - [x] UI: finish #9  (Kirill)
 - [x] UI: review proposed localization strategy (Bridget) (#22)
 - [x] UI: review popup messaging (Bridget) (#30)
 - [x] UI: review grammar/resourcequery code (Kirill)
 
Additional, lower priority, if there is time:
 - [x] Add Greek grammar (Bridget)
 - [ ] Inflection Tables: Link Column Headings to Grammar (Kirill, with assistance from Bridget)
 - [ ] Latin Inflection Tables: Add irregular forms (Bridget, with assistance from Kirill)
 - [ ] Greek Inflection Tables: Add missing major parts of speech (Kirill, with assistance from Bridget)
 - [ ] Latin Inflection Tables: Add missing major parts of speech (Kirill)
